apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../../kustomize/base/backend/express-deployment.yaml
- ../../../kustomize/base/backend/express-service.yaml
